"""Composite ChatDev's character PNGs into one sprite sheet.

ChatDev ships 144 PNGs (12 characters x 4 directions x 3 frames), each a
large transparent render. Serving 144 separate images over HTTP is far too
slow for the demo page, and the source art is 850px tall - far bigger than
the 16px tile grid needs.

So we crop, scale and pack them into one small sheet that gets base64'd
straight into bazaar_live.html. No network requests, no CORS, no CDN.

Layout:  rows = role (6), columns = direction*3 + frame (12)
         cell = 28 x 44 px, character bottom-aligned so feet stay on the
         tile regardless of how tall a given pose crops.

Per-character sizes differ (508x847, 459x793, 856x958, ...), so every
character is scaled to fit its own cell rather than being stretched to a
fixed grid, and the bounding box is taken across ALL of that character's
frames so a figure doesn't jitter as it walks.
"""
import base64
import json
import os

from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "assets", "chatdev_src")
OUT_PNG = os.path.join(ROOT, "assets", "chatdev_sheet.png")
OUT_JS = os.path.join(ROOT, "assets", "chatdev_sheet.js")

# role -> which of ChatDev's 12 characters to use.
# Picked so the six read as clearly different people at a glance:
#  4 = warm/gold, 2 = purple, 5 = navy blue, 1 = cyan/green,
#  3 = pink/cream, 8 = brown
ROLE_CHAR = {
    "KEEPER": 4,
    "PROF": 2,
    "GUARD": 5,
    "RITIKA": 1,
    "MEERA": 3,
    "ARJUN": 8,
}
ROLES = ["KEEPER", "PROF", "GUARD", "RITIKA", "MEERA", "ARJUN"]
DIRS = ["D", "L", "R", "U"]          # source naming: down, left, right, up
FRAMES = [1, 2, 3]

CELL_W, CELL_H = 28, 44


def alpha_box(img):
    return img.getchannel("A").getbbox()


def union_box(boxes):
    x0 = min(b[0] for b in boxes)
    y0 = min(b[1] for b in boxes)
    x1 = max(b[2] for b in boxes)
    y1 = max(b[3] for b in boxes)
    return (x0, y0, x1, y1)


def build_role(char):
    """Load a character's 12 frames, crop to a shared box, return them."""
    imgs, boxes = {}, []
    for d in DIRS:
        for f in FRAMES:
            p = os.path.join(SRC, f"{char}-{d}-{f}.png")
            if not os.path.exists(p):
                raise SystemExit(f"missing sprite: {p}")
            im = Image.open(p).convert("RGBA")
            imgs[(d, f)] = im
            boxes.append(alpha_box(im))
    box = union_box(boxes)
    return {k: im.crop(box) for k, im in imgs.items()}, box


def fit(im, cw, ch):
    """Scale im into a cw x ch cell preserving aspect; bottom-centred."""
    w, h = im.size
    s = min(cw / w, ch / h)
    nw, nh = max(1, round(w * s)), max(1, round(h * s))
    im = im.resize((nw, nh), Image.LANCZOS)
    cell = Image.new("RGBA", (cw, ch), (0, 0, 0, 0))
    cell.paste(im, ((cw - nw) // 2, ch - nh), im)
    return cell


def main():
    cols = len(DIRS) * len(FRAMES)          # 12
    rows = len(ROLES)                       # 6
    sheet = Image.new("RGBA", (cols * CELL_W, rows * CELL_H), (0, 0, 0, 0))

    print(f"cell {CELL_W}x{CELL_H}  sheet {cols*CELL_W}x{rows*CELL_H}\n")
    for r, role in enumerate(ROLES):
        char = ROLE_CHAR[role]
        frames, box = build_role(char)
        bw, bh = box[2] - box[0], box[3] - box[1]
        for di, d in enumerate(DIRS):
            for fi, f in enumerate(FRAMES):
                cell = fit(frames[(d, f)], CELL_W, CELL_H)
                sheet.paste(cell, ((di * len(FRAMES) + fi) * CELL_W, r * CELL_H))
        print(f"  {role:7} <- chatdev char {char:2}   "
              f"crop {bw}x{bh}")

    sheet.save(OUT_PNG, optimize=True)
    raw = open(OUT_PNG, "rb").read()
    b64 = base64.b64encode(raw).decode("ascii")

    meta = {
        "cellW": CELL_W, "cellH": CELL_H,
        "cols": cols, "rows": rows,
        "roles": ROLES,
        "dirs": DIRS,
        "frames": len(FRAMES),
        "roleChar": ROLE_CHAR,
    }
    with open(OUT_JS, "w", encoding="utf-8") as fh:
        fh.write("/* GENERATED by scripts/build_sprite_sheet.py - do not edit.\n")
        fh.write("   Source: ChatDev character sprites (OpenBMB/ChatDev, Apache-2.0).\n")
        fh.write("   Names SPR_META / SPR_B64 are what use_chatdev_sprites.py and the\n")
        fh.write("   page's sprBlit() expect - keep them in sync if you rename. */\n")
        fh.write(f"const SPR_META={json.dumps(meta, separators=(',', ':'))};\n")
        fh.write(f"const SPR_B64={json.dumps(b64)};\n")

    print(f"\nwrote {OUT_PNG}  ({len(raw)/1024:.0f} KB)")
    print(f"wrote {OUT_JS}  ({len(b64)/1024:.0f} KB base64)")


if __name__ == "__main__":
    main()
