"""Swap bazaar_live.html over to ChatDev's real character sprites.

The previous approach generated characters as ASCII grids (rows of letters
like 'OKSuuu...') that drawMap() painted pixel by pixel. That caps the
quality at whatever can be expressed in a 16x32 letter grid, which is why
it never looked like the reference.

This patch replaces the drawing path, not the data model:

  * every BODY_X grid collapses to a role marker {role:"X"}, so all the
    existing references (npcs, PERSONAS, SPEAKER_BODY, player.body) keep
    working unchanged,
  * drawActor() becomes a sprite-sheet blit: row = role, column =
    direction*3 + walk frame,
  * the feed-avatar drawMap() call becomes the same blit, scaled down.

The sheet is a base64 data URI, so there is no extra network request and no
dependency on the static file server.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HTML = ROOT / "bazaar_live.html"
SHEET_JS = ROOT / "assets" / "chatdev_sheet.js"

ROLES = ["KEEPER", "PROF", "GUARD", "RITIKA", "MEERA", "ARJUN"]

src = HTML.read_text(encoding="utf-8")
sheet_js = SHEET_JS.read_text(encoding="utf-8")

# ---------------------------------------------------------------- 1. data --
# Drop any sheet injected by an earlier run so this patch is re-runnable.
src = re.sub(r"/\* GENERATED by scripts/embed_sprite_sheet\.py.*?\nconst SPR_B64=\"[^\"]*\";\n",
             "", src, flags=re.S)

# The sheet decodes asynchronously even as a data URI, so the first frame or
# two can run before it is ready. drawActor guards on sprReady rather than
# throwing, and draws a plain silhouette until it is.
bridge = """
/* ---- ChatDev character sprite sheet (see scripts/build_sprite_sheet.py) ---- */
const sprImg=new Image();
let sprReady=false;
sprImg.onload=function(){ sprReady=true; };
sprImg.src="data:image/png;base64,"+SPR_B64;

const SPR_ROLE_IX={""" + ",".join(f'"{r}":{i}' for i, r in enumerate(ROLES)) + """};
const SPR_DIR_IX ={down:0,left:1,right:2,up:3};

/* Blit one character cell, feet standing on (px,py), horizontally centred. */
function sprBlit(c,role,dir,frame,px,py,scale){
  if(!sprReady) return false;
  scale=scale||1;
  const cw=SPR_META.cellW, ch=SPR_META.cellH;
  const w=cw*scale, h=ch*scale;
  const col=(SPR_DIR_IX[dir]||0)*SPR_META.frames + (frame%SPR_META.frames);
  const sx=col*cw, sy=(SPR_ROLE_IX[role]||0)*ch;
  c.drawImage(sprImg, sx,sy,cw,ch, Math.round(px-w/2), Math.round(py-h)+2, w,h);
  return true;
}
"""

anchor = "function drawActor(c,ent,pal,tweak){"
if anchor not in src:
    raise SystemExit("drawActor anchor not found")
src = src.replace(anchor, sheet_js + "\n" + bridge + "\n" + anchor, 1)


# ------------------------------------------------------- 2. role markers ---
def _repl_body(m):
    name = m.group(1)
    assert name in ROLES, f"unexpected body {name}"
    return f'const BODY_{name} = {{role:"{name}"}};'


src, n_bodies = re.subn(r"const BODY_(\w+) = \{.*?^\};",
                        _repl_body, src, flags=re.S | re.M)
if n_bodies != len(ROLES):
    raise SystemExit(f"replaced {n_bodies} BODY blocks, expected {len(ROLES)}")

# LEGS was the chibi stride block; nothing blits it any more.
src, n_legs = re.subn(r"/\* stride-frame leg block[^\n]*\nconst LEGS = \[.*?^\];\n",
                      "", src, flags=re.S | re.M)


# ---------------------------------------------------------- 3. drawActor ---
m = re.search(r"function drawActor\(c,ent,pal,tweak\)\{.*?^\}\n",
              src, flags=re.S | re.M)
if not m:
    raise SystemExit("could not locate drawActor body")
new_draw = (
    "function drawActor(c,ent,pal,tweak){\n"
    "  const role=(ent.body&&ent.body.role)||\"RITIKA\";\n"
    "  const px=Math.round(ent.px), py=Math.round(ent.py);\n"
    "  drawShadow(c,px,py);\n"
    "  if(!sprBlit(c,role,ent.dir,ent.frame||0,px,py,1)){\n"
    "    /* sheet still decoding - keep the slot occupied */\n"
    "    c.fillStyle=P.ink; c.fillRect(px-7,py-30,14,30);\n"
    "  }\n"
    "}\n"
)
src = src[:m.start()] + new_draw + src[m.end():]


# ----------------------------------------------------- 4. feed avatars -----
old_av = ('  drawMap(cv.getContext("2d"), '
          '(SPEAKER_BODY[who]||BODY).down.slice(), 0, 0, pal);')
new_av = (
    "  var _b=(SPEAKER_BODY[who]||BODY);\n"
    "  var _g=cv.getContext(\"2d\");\n"
    "  sprBlit(_g, (_b&&_b.role)||\"RITIKA\", \"down\", 0,\n"
    "          cv.width/2, cv.height+2, cv.height/SPR_META.cellH);"
)
if old_av in src:
    src = src.replace(old_av, new_av, 1)
    n_av = 1
else:
    print("  note: feed avatar call not in the expected form - left alone")
    n_av = 0

# ------------------------------------------------- 5. boot validation -----
# validateSprites() walked the ASCII grid rows (BODY[k].forEach) to warn about
# wrong row widths. With characters coming from the sheet there are no rows to
# walk, so it now checks the thing that can actually be wrong: that the sheet
# decoded and every role resolves to a real row.
OLD_VAL = re.search(
    r"/\* ---------------- boot ---------------- \*/\n"
    r"\(function validateSprites\(\)\{.*?\n\}\)\(\);\n",
    src, flags=re.S)
if OLD_VAL:
    NEW_VAL = (
        "/* ---------------- boot ---------------- */\n"
        "(function validateSprites(){\n"
        "  sprImg.addEventListener('load',function(){\n"
        "    const ok = sprImg.naturalWidth===SPR_META.cols*SPR_META.cellW &&\n"
        "               sprImg.naturalHeight===SPR_META.rows*SPR_META.cellH;\n"
        "    if(!ok) console.warn('sprite sheet size mismatch',\n"
        "                         sprImg.naturalWidth, sprImg.naturalHeight);\n"
        "  });\n"
        "  Object.keys(SPEAKER_BODY||{}).forEach(k=>{\n"
        "    if(!SPR_ROLE_IX.hasOwnProperty((SPEAKER_BODY[k]||{}).role))\n"
        "      console.warn('speaker has no sprite row:', k);\n"
        "  });\n"
        "})();\n"
    )
    src = src[:OLD_VAL.start()] + NEW_VAL + src[OLD_VAL.end():]
    n_val = 1
else:
    print("  note: validateSprites block not found - left alone")
    n_val = 0

HTML.write_text(src, encoding="utf-8")
print(f"patched {HTML.name}  ({len(src)/1024:.0f} KB)")
print(f"  BODY grids -> role markers : {n_bodies}")
print(f"  LEGS block removed         : {n_legs}")
print(f"  feed avatar re-blitted     : {n_av}")

for must in ("SPR_B64", "SPR_META", "sprBlit", 'role:"KEEPER"', "sprReady"):
    assert must in src, f"post-check failed: {must} missing"
print("post-check: all new symbols present")
